services:
  mysql:
    image: mysql:8.0

    container_name: hospital_mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: hospital_db
      MYSQL_USER: hospital_user
      MYSQL_PASSWORD: hospital123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
